FROM golang:1.18 as builder

WORKDIR /go/src/cacher

COPY . .

RUN go get -d -v ./...

RUN go build -o /app/cacher ./cmd/.

ENTRYPOINT ["/app/cacher", "--mode=client"]



















