version: '3.8'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'

  server:
    build:
      context: .
      dockerfile: Dockerfile_server
    image: server
    depends_on:
      - redis
    ports:
      - "50005:50005"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

  client:
    build:
      context: .
      dockerfile: Dockerfile_client
    image: client
    depends_on:
      - server

networks:
  default:
    name: cacher
    driver: bridge